baseURL = "https://philmish.github.io/"

theme = "LoveIt"

title = "cat /usr/share"

languageCode = "en-us"
languageName  = "English"

[author]
name = "philmish"
link = "https://philmish.github.io/"

[menu]
    [[menu.main]]
        weight = 1
        identifier = "posts"
        pre = "<i class=\"fa-solid fa-file\"></i>"
        post = ""
        name = ""
        url = "/posts/"
        title = "Posts"
      [[menu.main]]
        weight = 2
        identifier = "tags"
        pre = "<i class=\"fa-solid fa-tag\"></i>"
        post = ""
        name = ""
        url = "/tags/"
        title = "Tags"
      [[menu.main]]
        weight = 3
        identifier = "categories"
        pre = "<i class=\"fa-solid fa-sitemap\"></i>"
        post = ""
        name = ""
        url = "/categories/"
        title = "Categories"

[params]
    defaultTheme = "dark"
    gitRepo = "https://github.com/dillonzq/LoveIt"
    fingerprint = ""
    dateFormat = "2006-01-02"
    title = "ls /usr/share"
    description = "A little bit of this and a little bit of that."
    images = ["/logo.png"]

    [params.header]
        desktopMode = "fixed"
        mobileMode = "auto"
        [params.header.title]
            logo = ""
            name = "ls /usr/share"
            pre = "<i class='fa-solid fa-terminal' aria-hidden='true'></i>"
            post = ""
            typeit = true

[params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2023
    icp = ""
    license= '<a rel="This is free and unencumbered software released into the public domain." href="https://unlicense.org" target="_blank">The Unlicense</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.app]
    title = "Philmish's Blog"
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "algolia"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "https://avatars.githubusercontent.com/u/92064198?v=4"
      title = "Hey folks,"
      subtitle = "I am a junior software developer interested in building tools, networks and security related topics. This place contains my writeups on projects and learning, as well as a collection of different info dumps for tools and stuff i am playing around with."
      typeit = false
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = false
      paginate = 6
  [params.social]
    GitHub         = "philmish"

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = true
    lightgallery = true
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = false
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 50
    [params.page.math]
      enable = false
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.comment]
      enable = false
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # someJavascript = "https://cdn.example.com/some.js"

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":year/:month/:filename"

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
