baseURL = "https://philmish.github.io/"
languageCode = "en-us"
title = "Philmish's Blog"
sectionPagesMenu = "burgermenu"

[author]
name = "philmish"
link = "https://philmish.github.io/"

[params]
    withHtmx = true

    [params.prism]
        languages = [
            "bash",
            "rust"
        ]
        plugins = [
            "command-line",
            "show-language"
        ]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[menu]
[[menu.burgermenu]]
    name = "Cheatsheets"
    url = "/cheatsheets"
[[menu.burgermenu]]
    name = "Learning"
    url = "/learning"
[[menu.burgermenu]]
    name = "Projects"
    url = "/projects"
