baseURL = "https://philmish.github.io/"
languageCode = "en-us"
title = "Philmish's Blog"
sectionPagesMenu = "burgermenu"

[author]
name = "philmish"
link = "https://philmish.github.io/"

[params]
    withHtmx = true

[markup]
    [markup.highlight]
        anchorLineNos = false     
        codeFences = true     
        guessSyntax = false     
        hl_Lines = ''     
        hl_inline = false     
        lineAnchors = ''     
        lineNoStart = 1     
        lineNos = false     
        lineNumbersInTable = true     
        noClasses = true     
        noHl = false     
        style = 'monokai'     
        tabWidth = 4 
